name: Attach Docker Image to Release

on:
  release:
    types: [published, edited]

permissions:
  contents: write  # Required for uploading release assets

jobs:
  build-and-attach:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run tests
        if: ${{ github.event.release.prerelease }}
        run: |
            echo "Doing validations, etc. on draft release for '${{ github.event.release.tag_name }}'..."
            # Add any test commands here
            # e.g., ./run-tests.sh, build docker container
    
      - name: Pull Docker image
        if: ${{ !github.event.release.prerelease }}
        run: |
          ./scripts/createReleasePackage.sh ${{ github.event.release.tag_name }}

      - name: Upload Docker image as release asset
        if: ${{ !github.event.release.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" /tmp/My-App-v${{ github.event.release.tag_name }}.zip --repo "${{ github.repository }}" --clobber
